[package]
name = "utp-dojo"
version = "0.1.0"
cairo-version = "2.4.0"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.4.0" }

[[target.dojo]]
lib = "src/lib.cairo"
