[indexing]
contracts = [
  "erc20:0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7", # ETH fee token
  "erc20:0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d", # STRK fee token
]
<<<<<<< HEAD
[sql]
historical = ["dojo_starter-Moves", "dojo_starter-Moved"]

=======

controllers = true
world_block = 0
transactions = true

[sql]
historical = ["utp_dojo-PlayerPosition", "utp_dojo-ShipPosition"]

[events]
raw = true
>>>>>>> e3537f9dba4db69172bacd52d855a24fef64c13b
